version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=user-login-inforamation
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata/user-database:/var/lib/postgresql/data

  nginx:
    depends_on:
      - auth
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"

  auth:
    depends_on:
      - db

    build:
      dockerfile: Dockerfile.dev
      context: ./auth
    volumes:
      - ./auth:/app
      - ./image-repository:/app/image-repository

  write-information:
    depends_on:
      - db

    build:
      dockerfile: Dockerfile.dev
      context: ./write-information
    volumes:
      - ./write-information:/app
      - ./image-repository:/app/image-repository

  read-information:
    depends_on:
      - db

    build:
      dockerfile: Dockerfile.dev
      context: ./read-information
    volumes:
      - ./read-information:/app
      - ./image-repository:/app/image-repository

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
